
policy: 
  name: act
  args: 
    model_path: /home/agilex/ainnovation/cobot_magic/models_good/joint_transfer_coke_fixed_front_121/policy_best.ckpt
    pkl_path: /home/agilex/ainnovation/cobot_magic/models_good/joint_transfer_coke_fixed_front_121/dataset_stats.pkl
    history_horizon: 1
    robot_type: 1


service:
  ip: '0.0.0.0'
  port: 61055
  log: 'service.log'
  workers: 10

robot:
  robot_type: "ALOHA_HFLR"
  action_encoding: "JOINT_POS_BIMANUAL_ABS"
  state_encoding: "JOINT_BIMANUAL"
  connection_keep_alive: 3600 #保持存活时间，以秒为单位，过期自动清理状态. (客户端无通信后，保留机器人会话状态的最长时间.)


  
  

