version: 1  
disable_existing_loggers: false  
formatters:  
  standard:  
    #format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"  
    format: "[%(asctime)s][%(filename)s:%(lineno)d][%(levelname)s]: %(message)s"  
handlers:  
  console:  
    level: DEBUG  
    class: logging.StreamHandler  
    formatter: standard  
    stream: ext://sys.stdout  
  file:  
    level: INFO  
    class: logging.handlers.RotatingFileHandler  
    formatter: standard  
    filename: server.log  
    maxBytes: 104857600  
    backupCount: 20  
    encoding: utf8  
root:  
  level: INFO  
  handlers: [console,file]