# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vla_server_pb2 as vla__server__pb2


class RobotServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRobot = channel.unary_unary(
                '/vla_server.RobotService/CreateRobot',
                request_serializer=vla__server__pb2.CreateRobotRequest.SerializeToString,
                response_deserializer=vla__server__pb2.CreateRobotResponse.FromString,
                )
        self.ProcessRobotRequest = channel.unary_unary(
                '/vla_server.RobotService/ProcessRobotRequest',
                request_serializer=vla__server__pb2.RobotRequest.SerializeToString,
                response_deserializer=vla__server__pb2.RobotResponse.FromString,
                )


class RobotServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRobot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessRobotRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRobot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRobot,
                    request_deserializer=vla__server__pb2.CreateRobotRequest.FromString,
                    response_serializer=vla__server__pb2.CreateRobotResponse.SerializeToString,
            ),
            'ProcessRobotRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessRobotRequest,
                    request_deserializer=vla__server__pb2.RobotRequest.FromString,
                    response_serializer=vla__server__pb2.RobotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vla_server.RobotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RobotService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRobot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vla_server.RobotService/CreateRobot',
            vla__server__pb2.CreateRobotRequest.SerializeToString,
            vla__server__pb2.CreateRobotResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProcessRobotRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vla_server.RobotService/ProcessRobotRequest',
            vla__server__pb2.RobotRequest.SerializeToString,
            vla__server__pb2.RobotResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
